# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timer_dialog.ui'
#
# Created: Mon Jan 25 15:28:16 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from Qt.QtWidgets import *
from Qt.QtCore import *
from Qt.QtGui import *

class Ui_maya_save_timer_dlg(object):
    def setupUi(self, maya_save_timer_dlg):
        maya_save_timer_dlg.setObjectName("maya_save_timer_dlg")
        maya_save_timer_dlg.resize(476, 129)
        self.verticalLayout = QVBoxLayout(maya_save_timer_dlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_zh_1 = QLabel(maya_save_timer_dlg)
        font = QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_zh_1.setFont(font)
        self.label_zh_1.setObjectName("label_zh_1")
        self.horizontalLayout.addWidget(self.label_zh_1)
        self.time_label = QLabel(maya_save_timer_dlg)
        font = QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.time_label.setFont(font)
        self.time_label.setObjectName("time_label")
        self.horizontalLayout.addWidget(self.time_label)
        self.label_zh_2 = QLabel(maya_save_timer_dlg)
        font = QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_zh_2.setFont(font)
        self.label_zh_2.setObjectName("label_zh_2")
        self.horizontalLayout.addWidget(self.label_zh_2)
        spacerItem1 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_en_1 = QLabel(maya_save_timer_dlg)
        font = QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_en_1.setFont(font)
        self.label_en_1.setObjectName("label_en_1")
        self.horizontalLayout_3.addWidget(self.label_en_1)
        self.time_label_1 = QLabel(maya_save_timer_dlg)
        font = QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.time_label_1.setFont(font)
        self.time_label_1.setObjectName("time_label_1")
        self.horizontalLayout_3.addWidget(self.time_label_1)
        self.label_2 = QLabel(maya_save_timer_dlg)
        font = QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.save_btn = QPushButton(maya_save_timer_dlg)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_2.addWidget(self.save_btn)
        self.versionup_btn = QPushButton(maya_save_timer_dlg)
        self.versionup_btn.setObjectName("versionup_btn")
        self.horizontalLayout_2.addWidget(self.versionup_btn)
        self.cancel_btn = QPushButton(maya_save_timer_dlg)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 2)

        self.retranslateUi(maya_save_timer_dlg)
        self.cancel_btn.clicked.connect(maya_save_timer_dlg.close)
        self.save_btn.clicked.connect(maya_save_timer_dlg.close)
        self.versionup_btn.clicked.connect(maya_save_timer_dlg.close)
        QMetaObject.connectSlotsByName(maya_save_timer_dlg)

    def retranslateUi(self, maya_save_timer_dlg):
        try:
            maya_save_timer_dlg.setWindowTitle(QApplication.translate("maya_save_timer_dlg", "温馨提示", None, QApplication.UnicodeUTF8))
            self.label_zh_1.setText(QApplication.translate("maya_save_timer_dlg", "您已持续", None, QApplication.UnicodeUTF8))
            self.time_label.setText(QApplication.translate("maya_save_timer_dlg", "20", None, QApplication.UnicodeUTF8))
            self.label_zh_2.setText(QApplication.translate("maya_save_timer_dlg", "分钟未保存文件。", None, QApplication.UnicodeUTF8))
            self.label_en_1.setText(QApplication.translate("maya_save_timer_dlg", "You have not saved your file for", None, QApplication.UnicodeUTF8))
            self.time_label_1.setText(QApplication.translate("maya_save_timer_dlg", "20", None, QApplication.UnicodeUTF8))
            self.label_2.setText(QApplication.translate("maya_save_timer_dlg", "minutes.", None, QApplication.UnicodeUTF8))
            self.save_btn.setText(QApplication.translate("maya_save_timer_dlg", "Save", None, QApplication.UnicodeUTF8))
            self.versionup_btn.setText(QApplication.translate("maya_save_timer_dlg", "Version Up", None, QApplication.UnicodeUTF8))
            self.cancel_btn.setText(QApplication.translate("maya_save_timer_dlg", "Cancel", None, QApplication.UnicodeUTF8))
        except:
            maya_save_timer_dlg.setWindowTitle(QApplication.translate("maya_save_timer_dlg", "温馨提示", None))
            self.label_zh_1.setText(QApplication.translate("maya_save_timer_dlg", "您已持续", None))
            self.time_label.setText(QApplication.translate("maya_save_timer_dlg", "20", None))
            self.label_zh_2.setText(QApplication.translate("maya_save_timer_dlg", "分钟未保存文件。", None))
            self.label_en_1.setText(QApplication.translate("maya_save_timer_dlg", "You have not saved your file for", None))
            self.time_label_1.setText(QApplication.translate("maya_save_timer_dlg", "20", None))
            self.label_2.setText(QApplication.translate("maya_save_timer_dlg", "minutes.", None))
            self.save_btn.setText(QApplication.translate("maya_save_timer_dlg", "Save", None))
            self.versionup_btn.setText(QApplication.translate("maya_save_timer_dlg", "Version Up", None))
            self.cancel_btn.setText(QApplication.translate("maya_save_timer_dlg", "Cancel", None))

