# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'timer_dialog.ui'
#
# Created: Mon Jan 25 15:28:16 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_maya_save_timer_dlg(object):
    def setupUi(self, maya_save_timer_dlg):
        maya_save_timer_dlg.setObjectName("maya_save_timer_dlg")
        maya_save_timer_dlg.resize(476, 129)
        self.verticalLayout = QtGui.QVBoxLayout(maya_save_timer_dlg)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_zh_1 = QtGui.QLabel(maya_save_timer_dlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_zh_1.setFont(font)
        self.label_zh_1.setObjectName("label_zh_1")
        self.horizontalLayout.addWidget(self.label_zh_1)
        self.time_label = QtGui.QLabel(maya_save_timer_dlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.time_label.setFont(font)
        self.time_label.setObjectName("time_label")
        self.horizontalLayout.addWidget(self.time_label)
        self.label_zh_2 = QtGui.QLabel(maya_save_timer_dlg)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_zh_2.setFont(font)
        self.label_zh_2.setObjectName("label_zh_2")
        self.horizontalLayout.addWidget(self.label_zh_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_en_1 = QtGui.QLabel(maya_save_timer_dlg)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_en_1.setFont(font)
        self.label_en_1.setObjectName("label_en_1")
        self.horizontalLayout_3.addWidget(self.label_en_1)
        self.time_label_1 = QtGui.QLabel(maya_save_timer_dlg)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.time_label_1.setFont(font)
        self.time_label_1.setObjectName("time_label_1")
        self.horizontalLayout_3.addWidget(self.time_label_1)
        self.label_2 = QtGui.QLabel(maya_save_timer_dlg)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.save_btn = QtGui.QPushButton(maya_save_timer_dlg)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_2.addWidget(self.save_btn)
        self.versionup_btn = QtGui.QPushButton(maya_save_timer_dlg)
        self.versionup_btn.setObjectName("versionup_btn")
        self.horizontalLayout_2.addWidget(self.versionup_btn)
        self.cancel_btn = QtGui.QPushButton(maya_save_timer_dlg)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_2.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 2)

        self.retranslateUi(maya_save_timer_dlg)
        QtCore.QObject.connect(self.cancel_btn, QtCore.SIGNAL("clicked()"), maya_save_timer_dlg.close)
        QtCore.QObject.connect(self.save_btn, QtCore.SIGNAL("clicked()"), maya_save_timer_dlg.close)
        QtCore.QObject.connect(self.versionup_btn, QtCore.SIGNAL("clicked()"), maya_save_timer_dlg.close)
        QtCore.QMetaObject.connectSlotsByName(maya_save_timer_dlg)

    def retranslateUi(self, maya_save_timer_dlg):
        maya_save_timer_dlg.setWindowTitle(QtGui.QApplication.translate("maya_save_timer_dlg", "温馨提示", None, QtGui.QApplication.UnicodeUTF8))
        self.label_zh_1.setText(QtGui.QApplication.translate("maya_save_timer_dlg", "您已持续", None, QtGui.QApplication.UnicodeUTF8))
        self.time_label.setText(QtGui.QApplication.translate("maya_save_timer_dlg", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label_zh_2.setText(QtGui.QApplication.translate("maya_save_timer_dlg", "分钟未保存文件。", None, QtGui.QApplication.UnicodeUTF8))
        self.label_en_1.setText(QtGui.QApplication.translate("maya_save_timer_dlg", "You have not saved your file for", None, QtGui.QApplication.UnicodeUTF8))
        self.time_label_1.setText(QtGui.QApplication.translate("maya_save_timer_dlg", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("maya_save_timer_dlg", "minutes.", None, QtGui.QApplication.UnicodeUTF8))
        self.save_btn.setText(QtGui.QApplication.translate("maya_save_timer_dlg", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.versionup_btn.setText(QtGui.QApplication.translate("maya_save_timer_dlg", "Version Up", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_btn.setText(QtGui.QApplication.translate("maya_save_timer_dlg", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

